run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - goconst
    - gocyclo
    - dupl
    - misspell
    - unparam
    - nakedret
    - prealloc
    - scopelint
    - gocritic
    - gochecknoinits
    - gochecknoglobals
    - gosec
    - funlen
    - whitespace
    - wsl
    - goprintffuncname
    - gomnd
    - lll
    - goerr113
    - godot
    - testpackage
    - nestif
    - exportloopref
    - exhaustive
    - sqlclosecheck
    - nolintlint
    - bodyclose

  disable:
    - depguard
    - dogsled
    - gocognit
    - godox
    - maligned
    - interfacer

linters-settings:
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  funlen:
    lines: 100
    statements: 50
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - return
        ignored-numbers:
          - '0'
          - '1'
          - '2'
          - '10'
          - '100'
  
  lll:
    line-length: 120
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
    
    # Exclude known issues in vendor folder
    - path: vendor/
      linters:
        - typecheck
        - unused
        - deadcode
    
    # Exclude generated files
    - path: \.pb\.go
      linters:
        - golint
    
    # Exclude benchmarks from some checks
    - path: _test\.go
      text: "^Benchmark"
      linters:
        - funlen
        - gomnd

  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 3
  
  # Show only new issues created after git revision
  new: false