name: Benchmarks

on:
  release:
    types: [created, published]
  workflow_dispatch:

jobs:
  benchmarks:
    name: Performance Benchmarks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'
        cache: true
        cache-dependency-path: go.sum

    - name: Run benchmarks
      run: |
        # Run benchmarks and save results (excluding examples)
        go test -bench=. -benchmem -benchtime=10s -count=3 -cpu=1,2,4 \
          ./pkg/... ./internal/... | tee benchmark_results.txt

    - name: Parse benchmark results
      run: |
        echo "## Benchmark Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        grep -E "^Benchmark" benchmark_results.txt >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark_results.txt

    - name: Add release information
      if: github.event_name == 'release'
      run: |
        echo "## Release Information" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Release Tag:** ${{ github.event.release.tag_name }}" >> $GITHUB_STEP_SUMMARY
        echo "**Release Name:** ${{ github.event.release.name }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

    - name: Memory profiling
      run: |
        # Run memory profiling (excluding examples)
        go test -bench=BenchmarkFlexLogBasic -benchmem -memprofile=mem.prof -cpuprofile=cpu.prof \
          ./pkg/... ./internal/... || true
        
        # Analyze memory profile if exists
        if [ -f mem.prof ]; then
          go tool pprof -top mem.prof | head -20 > mem_profile.txt
          
          echo "## Memory Profile (Top 20)" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          cat mem_profile.txt >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
        fi