name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  benchmarks:
    name: Performance Benchmarks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'
        cache: true
        cache-dependency-path: go.sum

    - name: Run benchmarks
      run: |
        # Run benchmarks and save results (excluding examples)
        go test -bench=. -benchmem -benchtime=10s -count=3 -cpu=1,2,4 \
          ./pkg/... ./internal/... | tee benchmark_results.txt

    - name: Parse benchmark results
      run: |
        echo "## Benchmark Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        grep -E "^Benchmark" benchmark_results.txt >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark_results.txt

    - name: Compare with baseline (PR only)
      if: github.event_name == 'pull_request'
      run: |
        # Checkout main branch for comparison
        git fetch origin ${{ github.base_ref }}
        git checkout origin/${{ github.base_ref }}
        
        # Run benchmarks on base branch (excluding examples)
        go test -bench=. -benchmem -benchtime=10s -count=1 \
          ./pkg/... ./internal/... | tee benchmark_baseline.txt
        
        # Checkout PR branch again
        git checkout -
        
        # Simple comparison
        echo "## Benchmark Comparison" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Baseline (${{ github.base_ref }} branch):" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        grep -E "^Benchmark" benchmark_baseline.txt | head -10 >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Current (PR branch):" >> $GITHUB_STEP_SUMMARY  
        echo "```" >> $GITHUB_STEP_SUMMARY
        grep -E "^Benchmark" benchmark_results.txt | head -10 >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY

    - name: Memory profiling
      run: |
        # Run memory profiling (excluding examples)
        go test -bench=BenchmarkFlexLogBasic -benchmem -memprofile=mem.prof -cpuprofile=cpu.prof \
          ./pkg/... ./internal/... || true
        
        # Analyze memory profile if exists
        if [ -f mem.prof ]; then
          go tool pprof -top mem.prof | head -20 > mem_profile.txt
          
          echo "## Memory Profile (Top 20)" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          cat mem_profile.txt >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
        fi